#!/usr/bin/env node
/* SessionEnd hook — refresh HEALTH.md from actual vault state.
 * Safe: writes HEALTH.md only; never modifies topics.
 * If HEALTH.md is missing required fields, rebuilds them.
 * Appends a weekly-review nag if days_since_review > 7.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const VAULT = 'C:\\Users\\rjain\\OneDrive - Technijian, Inc\\Documents\\obsidian\\tech-legal';
const MEM = path.join(VAULT, 'claude-memory');
const TOPICS = path.join(MEM, 'topics');
const HEALTH = path.join(MEM, 'HEALTH.md');
const LOG = path.join(MEM, '.retrieval-log.jsonl');
const CHANGELOG = path.join(MEM, 'CHANGELOG.md');

if (!fs.existsSync(MEM) || !fs.existsSync(TOPICS)) {
  process.exit(0);
}

function daysBetween(d1, d2) {
  return Math.floor((d2 - d1) / (1000 * 60 * 60 * 24));
}

function parseFrontmatter(content) {
  const m = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) return {};
  const fm = {};
  for (const line of m[1].split(/\r?\n/)) {
    const mm = line.match(/^([a-zA-Z_]+):\s*(.*)$/);
    if (mm) fm[mm[1]] = mm[2].trim();
  }
  return fm;
}

function wordCount(s) {
  return (s.match(/\b\w+\b/g) || []).length;
}

const topicFiles = fs.existsSync(TOPICS)
  ? fs.readdirSync(TOPICS).filter(f => f.endsWith('.md'))
  : [];

const topics = topicFiles.map(f => {
  const content = fs.readFileSync(path.join(TOPICS, f), 'utf8');
  const fm = parseFrontmatter(content);
  return { file: f, fm, words: wordCount(content) };
});

const volatility = { stable: 0, evolving: 0, ephemeral: 0 };
topics.forEach(t => {
  const v = t.fm.volatility || 'evolving';
  if (volatility[v] !== undefined) volatility[v]++;
});

const totalWords = topics.reduce((a, b) => a + b.words, 0);
const avgWords = topics.length ? Math.round(totalWords / topics.length) : 0;
const maxWords = topics.reduce((a, b) => Math.max(a, b.words), 0);

const neverAccessed = topics.filter(t => (parseInt(t.fm.access_count || '0', 10)) === 0).length;

const today = new Date();
function parseDate(s) {
  if (!s) return null;
  const d = new Date(s);
  return Number.isFinite(d.getTime()) ? d : null;
}
const stale60 = topics.filter(t => {
  const d = parseDate(t.fm.last_updated);
  return d && daysBetween(d, today) > 60;
}).length;
const stale180 = topics.filter(t => {
  const d = parseDate(t.fm.last_updated);
  return d && daysBetween(d, today) > 180;
}).length;

let logLines = 0;
try {
  const raw = fs.readFileSync(LOG, 'utf8');
  logLines = raw.split(/\r?\n/).filter(l => l.trim().length).length;
} catch (e) { /* empty log */ }

let daysSinceReview = null;
try {
  const health = fs.readFileSync(HEALTH, 'utf8');
  const m = health.match(/Last `\/review` run:\*\*\s*([0-9-]+)/);
  if (m) {
    const d = new Date(m[1]);
    if (Number.isFinite(d.getTime())) daysSinceReview = daysBetween(d, today);
  }
} catch (e) { /* no prior HEALTH */ }

const status = (topics.length > 400) ? 'RED' :
  (topics.length > 150 || stale180 > topics.length * 0.25) ? 'YELLOW' : 'GREEN';

const todayISO = today.toISOString().slice(0, 10);
const reviewNote = (daysSinceReview === null) ? 'never (baseline)' :
  (daysSinceReview > 21) ? `${daysSinceReview} days — vault health cannot be trusted, run /review` :
  (daysSinceReview > 14) ? `${daysSinceReview} days — overdue` :
  (daysSinceReview > 7)  ? `${daysSinceReview} days — review soon` :
  `${daysSinceReview} days`;

const body = `---
kind: health
last_updated: ${todayISO}
status: ${status}
baseline: ${logLines < 30 ? 'reconstructed' : 'live'}
---

# Vault Health

Live dashboard for \`claude-memory/\`. Regenerated by the SessionEnd hook.

## Weekly Review Status

- **Last \`/review\` run:** ${reviewNote}
- **Days since last review:** ${daysSinceReview === null ? 'n/a' : daysSinceReview}
- **Unresolved contradictions:** (run \`/contradictions\` to count)

## Size

| Metric | Value |
|---|---|
| Topic page count | ${topics.length} |
| Total word count | ${totalWords} |
| Average page size | ${avgWords} words |
| Max page size | ${maxWords} words |

## Retrieval Quality

| Metric | Value | Notes |
|---|---|---|
| Retrieval log lines | ${logLines} | ${logLines < 30 ? 'seed / reconstructed' : 'live'} |
| Never-accessed topics | ${neverAccessed} | |

## Freshness

| Metric | Value |
|---|---|
| Stale >60 days | ${stale60} |
| Stale >180 days | ${stale180} |

## Volatility Distribution

| Tier | Count | % |
|---|---|---|
| stable | ${volatility.stable} | ${topics.length ? Math.round(volatility.stable/topics.length*100) : 0}% |
| evolving | ${volatility.evolving} | ${topics.length ? Math.round(volatility.evolving/topics.length*100) : 0}% |
| ephemeral | ${volatility.ephemeral} | ${topics.length ? Math.round(volatility.ephemeral/topics.length*100) : 0}% |

## Classification

**${status}** — based on topic count (${topics.length}) and staleness (${stale180} stale >180d of ${topics.length}).
`;

fs.writeFileSync(HEALTH, body, 'utf8');

// Nag to stderr when review is overdue
if (daysSinceReview !== null && daysSinceReview > 7) {
  const banner = (daysSinceReview > 21)
    ? `[vault] WEEKLY REVIEW ${daysSinceReview} DAYS OVERDUE — /graduate will refuse recommendations. Run /review.`
    : (daysSinceReview > 14)
      ? `[vault] Weekly review ${daysSinceReview} days overdue. Run /review soon.`
      : `[vault] Weekly review due (${daysSinceReview} days since last). Run /review.`;
  process.stderr.write(banner + '\n');
}

process.exit(0);
